#!/bin/bash
set -euo pipefail
cd $(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)

TO=${1}

ssh pinging@$TO "mkdir -p ~/letsencrypt/config"
rsync -va -r ./configs/letsencrypt/config pinging@$TO:~/letsencrypt/
