#!/bin/bash
set -euo pipefail
cd $(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)

./scripts/build

HOST=${1}
LOCATION_DESCRIPTION=${2}

rsync -v frontend/dist/* pinging@$HOST:~/pinging/public/
if [[ "${ONLY_STATIC_FILES:-0}" == "1" ]]; then
    exit 0;
fi
# cp the binary over to tmp for faster rsync
ssh pinging@$HOST "mkdir -p ~/pinging; cp ~/pinging/pinging ~/pinging/pinging_tmp 2> /dev/null || true"
rsync -v ./configs/production.env pinging@$HOST:~/pinging/
rsync -v ./configs/pinging.service root@$HOST:/etc/systemd/system/
echo "$LOCATION_DESCRIPTION" > location_description_for_deploy.txt
rsync -v location_description_for_deploy.txt pinging@$HOST:~/pinging/location_description.txt
rm location_description_for_deploy.txt
rsync -v backend/target/release/pinging pinging@$HOST:~/pinging/pinging_tmp
ssh root@$HOST "setcap CAP_NET_BIND_SERVICE=+eip ~pinging/pinging/pinging_tmp && systemctl daemon-reload && mv ~pinging/pinging/pinging_tmp ~pinging/pinging/pinging && systemctl restart pinging"
