#!/bin/bash
set -euo pipefail

ZONE=${1}

gcloud compute instances create pinging-www-$(date +%s) --image-project=debian-cloud --image-family=debian-13 --zone ${ZONE} --machine-type e2-micro --project pinging
