#!/bin/bash
set -euo pipefail
cd $(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)

#sudo pacman -S --needed certbot
DIR=./configs/letsencrypt
echo "Use drill command to verify when DNS has propogated:"
echo "drill _acme-challenge.pinging.net TXT"
certbot certonly --manual --preferred-challenges=dns --agree-tos -d 'pinging.net' -d '*.pinging.net' -m pinging@benjamin-hansen.com --config-dir $DIR/config --work-dir $DIR/work/ --logs-dir $DIR/log/
