name: Docker build & push
on:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: ${{ github.event.repository.name }}
jobs:
  # Build and push the Docker image
  build-push:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    # Add required github permissions.
    permissions:
      contents: read
      id-token: write
      packages: write
    outputs:
      docker-tag: ${{ fromJSON(steps.meta.outputs.json).tags[1] }}
    steps:
      # Get the code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      # Set the builder to use Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Setup docker credentials
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Get metadata (version/tag) information
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,suffix=-{{sha}},event=branch
            type=ref,event=pr
            type=ref,suffix=-{{sha}},event=pr
            type=semver,pattern={{version}}
            type=semver,suffix=-{{sha}},pattern={{version}}
      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          target: run
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
